language: java
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name $GIT_USER
      - git config --local user.email $GIT_EMAIL
      - git tag "$TRAVIS_BRANCH-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  prerelease: true
  api_key: $GITHUB_TOKEN
  file: target/spark-outlier-jar-with-dependencies.jar
  skip_cleanup: true
  on:
    all_branches: true
